### ISSUE TITLE
Posts in the run up to OCaml 2014

### ISSUE THREAD

**Issue by amirmc** [ocaml/platform-blog#6]
The series of Platform posts in the run up to OCaml 2014, and shortly after.
All posts will go up on the new Platform blog at https://opam.ocaml.org/blog
This comment will be updated as things change/progress.

**Week 0**
- [x] OPAM 1.2 beta - **14 Aug** #2

**Week 1**
- [x] OPAM pinning @AltGr - **19 Aug** #11
- [x] DevTools I (Merlin/ocp-indent) - **21 Aug** #14

**Week 2**
- [x] DevTools II (UTop) - **26 Aug** #15
- [ ] opam2web @dsheets - **28 Aug**
- [ ] OPAM Pull Request workflow @samoht and @AltGr - **29 Aug?**

**Week 3**
- [x] Overview/Recap - @amirmc @avsm - **1 Sep** #9
- [ ] Assemblage by @samoht - **?** (draft in #16)

**Others**
- [ ] OPAM-doc @lpw25 - **?**
- [ ] Binary distribution via 0Install - @talex5 
- Testing - Part 1 (OCamlot) - **28 Aug**
- Testing - Part 2 (Travis/Flag) @avsm - **28 Aug**
- Ctypes
- Jenga
- IOCaml

**Comment by XVilka** [comment]
Maybe it worth to close this issue? It's 6 years old already and now irrelevant.
